version: '3.8'

services:
  meal_cnt_bot:
    build:
      context: .
    container_name: meal_cnt_bot
    volumes:
      - ./config:/app/config
    environment:
      - TZ=Asia/Seoul
    restart: always

